name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # No build steps needed for static HTML site

  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Optionally, if you want to lint HTML files
      - name: Lint HTML (optional)
        run: |
          npm install -g htmlhint
          htmlhint "**/*.html" --config .htmlhintrc

  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy to Vercel
        if: always()  # Example condition, replace with your actual condition
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_PROJECT_ID: OfH0wO6Rmr6llSRLaW6HE8oY  # Replace with your actual Vercel Project ID
          VERCEL_ORG_ID: team_rVXn4IOxY6GndQDKdErr254m   # Replace with your actual Vercel Team ID
        run: |
          npm install -g vercel
          vercel --token $VERCEL_TOKEN --prod --confirm --env VERCEL_PROJECT_ID=$VERCEL_PROJECT_ID --env VERCEL_ORG_ID=$VERCEL_ORG_ID --build-env VERCEL_URL=https://personal-profile-gold-delta.vercel.app/
